name: 'run-ghost-inspector-suite'
description: 'Runs a single ghost inspector suite and resolves based on test results (including screenshots)'
branding:
  icon: 'check'
  color: 'green'
inputs:
  vercelPreviewURL:
    description: 'Vercel preview URL, including https://'
    required: true
    default: 'UNDEFINED'
  suiteID:
    description: 'ghost inspector suiteID'
    required: true
    default: 'UNDEFINED'
  maxTimeout:
    description: 'in milliseconds. how long to wait for tests results before failing'
    required: false
    default: "300000"
  GHOST_INSPECTOR_API_KEY:
    description: 'ghost inspector API Key'
    required: true
    default: 'UNDEFINED'
outputs:
  resultURLs:
    description: 'The URLs of the suite(s) executed, delimited by newline'
  passed:
    description: '(boolean) whether the test passed'
runs:
  using: 'node12'
  main: 'index.js'